"""
Report generator.

Produces a structured research report as:
  - Plain text  (.txt)
  - Markdown    (.md)
  - PDF         (.pdf) via fpdf2
"""

from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from fpdf import FPDF

if TYPE_CHECKING:
    from research_agent.citations import CitationManager
    from research_agent.llm import GraniteClient, _WatsonxError
    from research_agent.summarizer import PaperSummary


# ---------------------------------------------------------------------------
# Report data model
# ---------------------------------------------------------------------------

class ResearchReport:
    """Holds all sections of a generated research report."""

    def __init__(self, topic: str) -> None:
        self.topic = topic
        self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.introduction: str = ""
        self.literature_review: str = ""
        self.methodology_overview: str = ""
        self.key_findings: str = ""
        self.hypotheses: str = ""
        self.conclusion: str = ""
        self.references: str = ""

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    def to_markdown(self) -> str:
        sections = [
            f"# Research Report: {self.topic}",
            f"*Generated: {self.generated_at} | Powered by IBM Granite (watsonx.ai)*",
            "",
            "---",
            "",
            "## 1. Introduction",
            self.introduction,
            "",
            "## 2. Literature Review",
            self.literature_review,
            "",
            "## 3. Methodology Overview",
            self.methodology_overview,
            "",
            "## 4. Key Findings",
            self.key_findings,
            "",
            "## 5. Suggested Hypotheses",
            self.hypotheses,
            "",
            "## 6. Conclusion",
            self.conclusion,
            "",
            "## References",
            self.references,
        ]
        return "\n".join(sections)

    def to_text(self) -> str:
        """Plain-text version (80-char wrapped)."""
        md = self.to_markdown()
        # Strip markdown symbols for plain text
        import re
        text = re.sub(r"^#{1,6}\s+", "", md, flags=re.MULTILINE)
        text = re.sub(r"\*{1,2}(.+?)\*{1,2}", r"\1", text)
        text = re.sub(r"---+", "─" * 60, text)
        return text


# ---------------------------------------------------------------------------
# PDF builder
# ---------------------------------------------------------------------------

class _ReportPDF(FPDF):
    """Custom FPDF subclass for report layout."""

    TITLE_COLOR = (30, 80, 180)
    HEADING_COLOR = (50, 50, 50)
    BODY_COLOR = (30, 30, 30)
    ACCENT_COLOR = (100, 100, 200)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self.ACCENT_COLOR)
        self.cell(0, 8, "IBM Granite Research Agent", align="R")
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Page {self.page_no()} | Generated by IBM Granite (watsonx.ai)", align="C")

    def chapter_title(self, title: str) -> None:
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.TITLE_COLOR)
        self.ln(4)
        self.cell(0, 9, title, ln=True)
        self.set_draw_color(*self.TITLE_COLOR)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_text_color(*self.BODY_COLOR)

    def body_text(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.BODY_COLOR)
        self.multi_cell(0, 5.5, text)
        self.ln(2)


# ---------------------------------------------------------------------------
# Report generator
# ---------------------------------------------------------------------------

class ReportGenerator:
    """
    Orchestrates IBM Granite calls to produce a full research report
    from a list of PaperSummary objects.
    """

    def __init__(self, llm: "GraniteClient", citation_mgr: "CitationManager") -> None:
        self._llm = llm
        self._citations = citation_mgr
        self._last_partial_report: "ResearchReport | None" = None

    def generate(
        self,
        topic: str,
        summaries: list["PaperSummary"],
    ) -> ResearchReport:
        """
        Build a complete ResearchReport for *topic* using *summaries*.

        Steps:
          1. Draft Introduction via Granite
          2. Draft Literature Review via Granite
          3. Draft Methodology Overview via Granite
          4. Aggregate Key Findings
          5. Suggest Hypotheses via Granite
          6. Draft Conclusion via Granite
          7. Format references

        If the IBM WML instance is inactive or any LLM call fails, each section
        falls back to a plain-text summary assembled from the paper abstracts so
        a complete (partial) report is always saved.
        """
        from research_agent.llm import _WatsonxError  # local import avoids circular

        report = ResearchReport(topic)
        papers_dicts = [
            {
                "title": s.title,
                "authors": s.authors,
                "year": s.year,
                "abstract": s.abstract,
            }
            for s in summaries
        ]
        summary_texts = [s.summary for s in summaries if s.summary]

        # Re-raise on the first LLM call so the error message surfaces cleanly;
        # subsequent sections fall back gracefully.
        llm_error: _WatsonxError | None = None

        def _section(name: str, fn, *args) -> str:
            nonlocal llm_error
            if llm_error is not None:
                return _fallback_section(name, summaries)
            try:
                return fn(*args)
            except _WatsonxError as exc:
                llm_error = exc
                return _fallback_section(name, summaries)

        report.introduction = _section(
            "Introduction", self._llm.generate_report_section, "Introduction", papers_dicts
        )
        report.literature_review = _section(
            "Literature Review", self._llm.generate_report_section, "Literature Review", papers_dicts
        )
        report.methodology_overview = _section(
            "Methodology Overview", self._llm.generate_report_section, "Methodology Overview", papers_dicts
        )
        report.key_findings = _section(
            "Key Findings", self._llm.generate_report_section, "Key Findings and Discussion", papers_dicts
        )
        report.hypotheses = _section(
            "Hypotheses", self._llm.suggest_hypotheses, topic, summary_texts
        )
        report.conclusion = _section(
            "Conclusion", self._llm.generate_report_section, "Conclusion", papers_dicts
        )

        # Register all papers and format reference list
        for s in summaries:
            self._citations.add_from_summary(s)
        report.references = self._citations.format_numbered_list()

        self._last_partial_report = report

        if llm_error is not None:
            raise llm_error

        return report

    # ------------------------------------------------------------------
    # Save helpers
    # ------------------------------------------------------------------

    def save_markdown(self, report: ResearchReport, output_dir: Path) -> Path:
        slug = _slugify(report.topic)
        path = output_dir / f"{slug}_report.md"
        path.write_text(report.to_markdown(), encoding="utf-8")
        return path

    def save_text(self, report: ResearchReport, output_dir: Path) -> Path:
        slug = _slugify(report.topic)
        path = output_dir / f"{slug}_report.txt"
        path.write_text(report.to_text(), encoding="utf-8")
        return path

    def save_pdf(self, report: ResearchReport, output_dir: Path) -> Path:
        slug = _slugify(report.topic)
        path = output_dir / f"{slug}_report.pdf"

        pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Cover
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(*_ReportPDF.TITLE_COLOR)
        pdf.multi_cell(0, 10, f"Research Report\n{report.topic}", align="C")
        pdf.ln(4)
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Generated: {report.generated_at}  |  IBM Granite (watsonx.ai)", align="C", ln=True)
        pdf.ln(6)

        sections = [
            ("1. Introduction", report.introduction),
            ("2. Literature Review", report.literature_review),
            ("3. Methodology Overview", report.methodology_overview),
            ("4. Key Findings", report.key_findings),
            ("5. Suggested Hypotheses", report.hypotheses),
            ("6. Conclusion", report.conclusion),
            ("References", report.references),
        ]
        for title, content in sections:
            pdf.chapter_title(title)
            pdf.body_text(content or "No content generated.")

        pdf.output(str(path))
        return path


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _slugify(text: str) -> str:
    import re
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "_", text)
    return text[:60]


def _fallback_section(section_name: str, summaries: list) -> str:
    """Build a plain-text section from paper abstracts when the LLM is unavailable."""
    lines = [f"[Auto-generated from paper abstracts — LLM unavailable]\n"]
    for s in summaries[:8]:
        title = getattr(s, "title", "Unknown")
        year = getattr(s, "year", "")
        abstract = getattr(s, "abstract", "") or getattr(s, "summary", "")
        lines.append(f"• {title} ({year}): {abstract[:300]}")
    return "\n".join(lines)
